# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC_Rating_Phase_Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_rate_cur_des', models.CharField(max_length=10)),
                ('ac_rate_cur_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Aux_Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_des', models.CharField(max_length=100)),
                ('power_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BIBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibo_des', models.CharField(max_length=500)),
                ('bibo_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Com_Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comport_des', models.CharField(max_length=500)),
                ('comport_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CTVT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctvt_des', models.CharField(max_length=500)),
                ('ctvt_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Frq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frq_des', models.CharField(max_length=10)),
                ('frq_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_des', models.CharField(max_length=500)),
                ('function_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_des', models.CharField(max_length=100)),
                ('lang_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_des', models.CharField(max_length=500)),
                ('outline_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_des', models.CharField(max_length=500)),
                ('protocol_code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_name', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='outline',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='language',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='function',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='frq',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='ctvt',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='com_port',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='bibo',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='aux_power',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
        migrations.AddField(
            model_name='ac_rating_phase_current',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RCF.Relay'),
        ),
    ]
