# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac_rating_phase_current',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='aux_power',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='bibo',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='com_port',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='ctvt',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='frq',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='function',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='language',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='outline',
            name='relay',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='relay',
        ),
    ]
