# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCF', '0002_auto_20171121_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inout_1_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout4_des', models.CharField(max_length=500)),
                ('inout4_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InOut_1_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout2_des', models.CharField(max_length=500)),
                ('inout2_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InOut_1_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout1_des', models.CharField(max_length=500)),
                ('inout1_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InOut_3_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inout3_des', models.CharField(max_length=500)),
                ('inout3_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameModel(
            old_name='AC_Rating_Phase_Current',
            new_name='CurrentRating',
        ),
        migrations.RenameModel(
            old_name='Aux_Power',
            new_name='Power',
        ),
        migrations.DeleteModel(
            name='BIBO',
        ),
        migrations.RenameField(
            model_name='currentrating',
            old_name='ac_rate_cur_code',
            new_name='cur_code',
        ),
        migrations.RenameField(
            model_name='currentrating',
            old_name='ac_rate_cur_des',
            new_name='cur_des',
        ),
    ]
