# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCF', '0005_auto_20171122_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inout_1',
            old_name='inout1_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_1',
            old_name='inout1_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_1',
            old_name='inout1_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_2',
            old_name='inout2_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_2',
            old_name='inout2_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_2',
            old_name='inout2_des',
            new_name='inout_des',
        ),
    ]
