# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCF', '0006_auto_20171122_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inout_3',
            old_name='inout3_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_3',
            old_name='inout3_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_3',
            old_name='inout3_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_4',
            old_name='inout4_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_4',
            old_name='inout4_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_4',
            old_name='inout4_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_5',
            old_name='inout5_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_5',
            old_name='inout5_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_5',
            old_name='inout5_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_6',
            old_name='inout6_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_6',
            old_name='inout6_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_6',
            old_name='inout6_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_7',
            old_name='inout7_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_7',
            old_name='inout7_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_7',
            old_name='inout7_des',
            new_name='inout_des',
        ),
        migrations.RenameField(
            model_name='inout_8',
            old_name='inout8_code',
            new_name='inout_code',
        ),
        migrations.RenameField(
            model_name='inout_8',
            old_name='inout8_config',
            new_name='inout_config',
        ),
        migrations.RenameField(
            model_name='inout_8',
            old_name='inout8_des',
            new_name='inout_des',
        ),
    ]
